In [13]:
import pandas as pd
import numpy as np

## Pandas

# series
# Dataframe

In [ ]:
#Series
a=pd.Series([10,20,30,40,60])
print(a)

0    10
1    20
2    30
3    40
4    60
dtype: int64

In [3]:
b=pd.Series(['sanmesh','ram','aniket','raj','rohit'])
b

0    sanmesh
1        ram
2     aniket
3        raj
4      rohit
dtype: str

In [12]:
#DataFrame
df=pd.DataFrame({
    'Name':['sam','ram','raj'],
    'Age':[23,14,34],
    'city':['pune','satara','sangli'],
    'salary':[19000,23000,17800]
})

df

  Name  Age    city  salary
0  sam   23    pune   19000
1  ram   14  satara   23000
2  raj   34  sangli   17800

In [16]:
s=np.random.randint(1,10,(4,4))
s

array([[1, 7, 4, 2],
       [9, 9, 7, 5],
       [4, 3, 7, 2],
       [8, 3, 9, 6]])

In [17]:
data=pd.DataFrame(s)
data

   0  1  2  3
0  1  7  4  2
1  9  9  7  5
2  4  3  7  2
3  8  3  9  6

In [22]:
a=np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
a
s=pd.DataFrame(a)
s

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [23]:
dic=({
    'Name':['aniket','sham','raj'],
    'Age':[23,14,34],
    'city':['pune','satara','sangli'],
    'salary':[39000,22000,17800]
})

df=pd.DataFrame(dic)
df

     Name  Age    city  salary
0  aniket   23    pune   39000
1    sham   14  satara   22000
2     raj   34  sangli   17800